### PR TITLE
Updated Starling to version 2.7

### PR DESCRIPTION
**Pull request by Shaunmax**
Fixed issue with maximum texture size

### CODE REVIEW

**Comment by yuhengh** [comment]
Can you make commit
[Raised the maximum texture size from 2048x2048 to 4096x4096](https://github.com/yuhengh/starling-builder-editor/pull/3/commits/b5678eef6b04e933a60135ac3bf370046a4ae460)
to its own pull request? I think that's the only change you need?

**Comment by Shaunmax** [comment]
I am sorry, I dint get you! 

I am new to git, I believe I have already committed the changes. Is there anything else to be done?

**Comment by yuhengh** [comment]
I would like to merge this commit
[Raised the maximum texture size from 2048x2048 to 4096x4096](https://github.com/yuhengh/starling-builder-editor/pull/3/commits/b5678eef6b04e933a60135ac3bf370046a4ae460)
but your pull request contains 2 commits.

I think you can edit this or create another pull request and choose only 1 commit. If not that's fine too I can merge it manually.

**Comment by Shaunmax** [comment]
OK! I dont know how to do that, so i did everything from scratch again and
have submitted a new pull request, please check and let me know.

**Pull request closed without merging**
